### ISSUE TITLE
Message to multiple User/All User

### ISSUE THREAD

**Issue by ukadmin** [matthiask/django-user-messages#5]
Hello, 
thanks for the Awesome Plugin. Works realy nice. Is there a way to send Message for alle Users?

Would be very nice. 

Thanks for sharing :)

**Comment by matthiask** [comment]
You'd have to create individual messages for every user. I think other apps exist if you wanted to send out alerts or something.

**Comment by ukadmin** [comment]
Okay thank's for your response

**Comment by matthiask** [comment]
My pleasure :)
